- hosts: "server1"
  become: yes
  vars_files:
    - vars/default.yml

  tasks:
    - name: install letsencrypt
      apt: name=letsencrypt state=latest

    - name: Create letsencrypt certificate
      shell: letsencrypt certonly -n --webroot -w /var/www/html -m {{ letsencrypt_email }} --agree-tos -d {{ domain_name }}
      args:
        creates: /etc/letsencrypt/live/{{ domain_name }}

    - name: Generate dhparams
      shell: openssl dhparam -out /etc/nginx/dhparams.pem 2048
      args:
        creates: /etc/nginx/dhparams.pem

    - name: Reload nginx to activate specified site
      service: name=nginx state=restarted