---
http_host: "veninsoft"
http_conf: "veninsoft.conf"
http_port: "80"
server_name: 167.172.189.29
document_root: /var/www/html
app_root: veninsoft
oauth_token: xxx
domain_name: veninsoft.com
letsencrypt_email: marian.venin@gmail.com
